name = "QuestionsMoodle"
uuid = "e6233ccc-e36c-49e3-ac71-1ad7b6c78055"
authors = ["Daniel Molina"]
version = "0.1.0"

[compat]
julia = "1.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
